name: CI

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        ruby:
          # - '2.6'
          # - '2.7'
          - '3.0'
          # - head
        rails:
          # - '6.0'
          - '6.1'
          # - head
    # continue-on-error: ${{ matrix.ruby == 'jruby' || matrix.ruby == 'head' || matrix.activerecord == 'head' }}
    name: Ruby ${{ matrix.ruby }} / Rails ${{ matrix.rails }}
    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_ALLOW_EMPTY_PASSWORD: yes
          MYSQL_DATABASE: alterity_test
        ports:
          - 3306:3306
        options: >-
          --health-cmd "mysqladmin ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    env:
       BUNDLE_GEMFILE: gemfiles/rails_${{ matrix.rails }}.gemfile
    steps:
      - uses: actions/checkout@v2
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          # bundler-cache: true
      - run: |
          bundle exec rake
        env:
          MYSQL_HOST: 127.0.0.1
          RAILS_ENV: test
